### ISSUE TITLE
Don't use .pkl files for `ProteusPy.data`  as they can become invalidated by code changes, use a more reproducible format like JSON

### ISSUE THREAD

**Issue by hmacdope** [suchanek/proteusPy#10]
Using pickles is a bit dangerous as they are only valid for a certain code version, ie ones with the exact same args and kwargs. You can use a compressed JSON or something similar instead.

**Comment by suchanek** [comment]
Hi,
I am reluctant to change this since the .pkl files represent the database itself and would require fundamental change to the codebase. I also do not know how to serialize the class into .json. The files are static, and are being read and written using well-defined and current pandas version. I don't expect them to change much at all, given the nature of the database.

**Comment by hmacdope** [comment]
Thats OK, if you don't think its feasible then I am happy to pass on this. Feel free to close the issue

**Comment by suchanek** [comment]
Thank you! 

P.S. I will address the other issues this week as times permits.
